### ISSUE TITLE
VerificationMethod type

### ISSUE THREAD

**Issue by julius-rennmann** [Gimly-Blockchain/eosio-did-resolver#13]
Regarding https://github.com/Gimly-Blockchain/eosio-did-resolver/pull/12 I have seen that @gimly-jack had to create several redundant interfaces to make the change from

```javascript
export interface VerificationMethod {
    id: string;
    type: string;
    controller: string;`
}
```

to

```javascript
export interface VerificationMethod {
    id: string;
    type: string[] | string;
    controller: string;`
}
```

to be able to implement the [verifiable conditions](https://github.com/w3c-ccg/verifiable-conditions) draft.
In the [eosio-did-spec](https://github.com/Gimly-Blockchain/eosio-did-spec#52-verification-methods) it is mentioned that this draft "is expected to become a W3C standard" which would also change the [DID spec](https://www.w3.org/TR/did-core/#verification-methods) allowing a set of strings for the verification method type, which would probably result in an analogue change in the [did-resolver](https://github.com/decentralized-identity/did-resolver) repository and in turn rid us from this nuisance.

My question is, when are we expecting this draft to become standard? Could we maybe provide a PR to the did-resolver repository to make this addition? I do not think they will accept that change yet as it does not conform to the DID spec.
Rewriting all these interfaces seems non intuitive and I would at least, if there is no other way, split them off into another file from where all original did-resolver as well as the changed ones are imported from to prevent confusion (I would do this, if considered sensible).

And I think the remodeled interfaces are not enough as of right now. In index.ts

```javascript
export function getResolver(): ResolverRegistry {
  return { 'eosio': resolve }
}
```

`resolve` is not a DIDResolver because the DIDResolutionResult is from one of these redefined interfaces, so DIDResolver must be redefined and then ResolverRegistry must be redefined. Then I think we are finished.

Sorry for the long text. What are your thoughts on this matter? Right now I would most likely create an intermediary file/adapter between did-resolver and eosio-did-resolver as mentioned above, including a comment explaining the "why". 

EDIT: See PR https://github.com/Gimly-Blockchain/eosio-did-resolver/pull/14

**Comment by ghost** [comment]
Thanks @Jaysolutely it's great you're keeping such a good watch!

In fact, as I implemented this I realized that [Verifiable Conditions](https://github.com/w3c-ccg/verifiable-conditions) does NOT comply to the DID-core standard. As such I took this to the [Credentials Community Group](https://www.w3.org/community/credentials/) (who's responsible for the work item which Gimly is leading) which it is a work item and discussed what we need to change it. Let me know if you want to see the email thread.

The result is this new issue to make Verifiable Conditions DID-core compliant. We are currently working on this strategy and you are welcome to join this discussion and help the work item
https://github.com/w3c-ccg/verifiable-conditions/issues/4

After this is resolved, we will need to make a small change to the EOSIO DID spec, and the implementation which can correctly conform to the [did-resolver](https://github.com/decentralized-identity/did-resolver) types.

Verifiable Conditions is currently a currently a rough draft work item, see the process here: https://docs.google.com/document/d/1vj811aUbs8GwZUNo-LIFBHafsz4rZTSnRtPv7RQaqNc/edit#heading=h.5o3nq8ktk0e2

**Comment by julius-rennmann** [comment]
Aha, so as I understand the Verifiable Conditions will be reworked to comply to DID-Core. Thus we will pause our attempts of implementing the current state till the Verifiable Conditions are compliant?

**Comment by ghost** [comment]
Yes we'll need to wait for this rework before finalizing I think. Hopefully that can happen in the next two weeks.

**Comment by theblockstalk** [comment]
these redundant types have been resolved by updating the VerifiableCondition spec
