### ISSUE TITLE
Create the DID Document from the eosio account 

### ISSUE THREAD

**Issue by ghost** [Gimly-Blockchain/eosio-did-resolver#3]
Complete the function. Fill out the id, controller, verificationMethod and service properties.

```js
function createDIDDocument(eosioAccount: any): DIDDocument {
    // TODO
    return { id: 'did:eosio:stub' };
}
```

https://github.com/Gimly-Blockchain/eosio-did-resolver/blob/master/src/resolver.ts#L14

**Comment by ghost** [comment]
Nearly finished in PR #12 
Still waiting on clarity from the EOSIO DID spec on key types, see issue https://github.com/Gimly-Blockchain/eosio-did-spec/issues/5

**Comment by theblockstalk** [comment]
Now finished in PR #21
