### ISSUE TITLE
Create a Universal Resolver driver

### ISSUE THREAD

**Issue by ghost** [Gimly-Blockchain/eosio-did-resolver#5]
1. Create a driver (docker container). We can copy most of this one, as we are using the same did-driver pattern. https://github.com/decentralized-identity/universal-resolver#drivers
2. Upload the driver to Docker hub
3. Create a PR to register the driver on https://github.com/decentralized-identity/universal-resolver#drivers

**Comment by ghost** [comment]
Can copy much of what is here
https://github.com/uport-project/uport-did-driver

**Comment by ghost** [comment]
uport did driver was forked here. please modify to work with the eosio-resolver
https://github.com/Gimly-Blockchain/eosio-did-driver
https://www.npmjs.com/package/eosio-did-resolver

please delete anything not currently a requirement to have

**Comment by theblockstalk** [comment]
created
https://github.com/Gimly-Blockchain/eosio-did-universal-resolver-driver
